### ISSUE TITLE
Kafka partitions setup with infinite retention

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#11]
The kafka partitions appear to be setup with infinite retention. As a result, my setup runs out of disk space with about a day of activity.

**Comment by nicholasstudt** [comment]
The docker as checked in is for local development use only, not a production configuration. Which is why it retains all messages allowing for debugging. If you require more disk space you may consider mounting the Kafka data directory to local storage so you are not constrained by the docker size itself.

**Comment by AndrewX192** [comment]
Got it, thank you for your advice.
