### ISSUE TITLE
Cannot SSH into v3 Hub

### ISSUE THREAD

**Issue by IrisWV** [arcus-smart-home/arcusplatform#45]
Built the dongle per instructions with my hub's .dbg file on a FAT32 thumb drive. Logged in with root username and the v3 password.  Access denied.

**Comment by AndrewX192** [comment]
I can confirm that this doesn't work on the v3 hub, however the instructions work fine for a v2 hub. At this moment, I think your best bet would be to have the hub update firmware via an arcus deployment and use that to root the hub. I might do this in a few weeks if we don't get an answer before then. In order to get Arcus working you only need to update 1 (or two, if you want to use without a USB stick) jar files in the agent code. If you use HTTP between the hub and the hub-bridge, you can use Arcus without making any changes.

If you want to tinker and don't want to wait, then you might look at getting a v2 hub. I recently scored one for $5 delivered on ebay.

**Comment by msilvermanks** [comment]
Fixed with https://github.com/arcus-smart-home/arcusplatform/commit/f6db99c54553a06ec3a76d10d85a0d12929557d7

**Comment by AndrewX192** [comment]
I can confirm that this is the correct password.

**Comment by msilvermanks** [comment]
cool thanks
